package com.codekotliners.memify.di

import android.content.Context
import com.codekotliners.memify.R
import com.codekotliners.memify.features.auth.di.GoogleWebClientId
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent

/**
 * Provides the Google Sign-In OAuth web client id to :feature:auth.
 *
 * The value comes from `R.string.default_web_client_id`, generated by the
 * google-services Gradle plugin only in this module (the only one with
 * google-services.json applied). See GoogleWebClientId for details.
 */
@Module
@InstallIn(SingletonComponent::class)
object GoogleAuthModule {
    @Provides
    @GoogleWebClientId
    fun provideGoogleWebClientId(@ApplicationContext context: Context): String =
        context.getString(R.string.default_web_client_id)
}
